wip
decentraland/decentraland-crypto pull request #36
Opened 2022-05-26 23:05 UTC by menduz

2022-05-29 14:26 UTC, nachomazzara commented on package.json
> -    "web3x": "^4.0.6"
see you in hell 👿

2022-05-29 19:19 UTC, menduz commented on package.json
> -    "web3x": "^4.0.6"
can I assume that is an approved PR?

2022-05-29 19:24 UTC, merged

2022-05-30 14:25 UTC, nachomazzara requested changes
Thanks @menduz 🎸

2022-05-30 14:25 UTC, nachomazzara commented on src/crypto.ts
> +// TODO: unit test
Oops

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet')
Can we use `https://rpc.decentraland.org/mainnet?project=dcl-crypto-test` so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +          provider: new HTTPProvider('https://rpc.decentraland.org/mainnet'),
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet')
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet'),
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet')
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet')
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +          provider: new HTTPProvider('https://rpc.decentraland.org/mainnet'),
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +          provider: new HTTPProvider('https://rpc.decentraland.org/mainnet'),
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet')
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +        new HTTPProvider('https://rpc.decentraland.org/mainnet'),
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
> +      const provider = new HTTPProvider('https://rpc.decentraland.org/mainnet')
Can we use https://rpc.decentraland.org/mainnet?project=dcl-crypto-test so we can discriminate the usage?

2022-05-30 14:25 UTC, nachomazzara commented on test/authenticator.spec.ts
>  })
I know that it was that way before but maybe we can move the RPC URL to a constant at the top of the file.